#!/usr/bin/env bash

VERSION=$(jq -r '.version' < info.json)
RELEASE_DIR="Bluegistics_${VERSION}"
ZIP_FILES=(info.json changelog.txt control.lua thumbnail.png)
ZIP_FILE="Bluegistics_${VERSION}.zip"

rm Bluegistics_*.zip

rm -rf ${RELEASE_DIR}
mkdir ${RELEASE_DIR}
cp ${ZIP_FILES[@]} ${RELEASE_DIR}

zip -r ${ZIP_FILE} ${RELEASE_DIR}
rm -rf ${RELEASE_DIR}
